version: '2'

networks:
  chef:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.0.101.0/24

services:
  ws:
    image: codespaces/chef-ws:v0.1.4
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
#    networks:
#      - chef
    container_name: ws
    domainname: codespaces.io
    hostname: ws
    restart: always

  node1:
    image: codespaces/chef-node-centos-6:v0.1.2
    ports:
       - "8081:8080"
    networks:
      chef:
        ipv4_address: 172.0.101.10
    container_name: node1
    domainname: codespaces.io
    hostname: node1
    restart: always

  node2:
    image: codespaces/chef-node-centos-6:v0.1.2
    ports:
       - "8082:8080"
    networks:
      chef:
        ipv4_address: 172.0.101.11
    container_name: node2
    domainname: codespaces.io
    hostname: node2
    restart: always

  node3:
    image: codespaces/chef-node-centos-6:v0.1.2
    ports:
      - "8083:8080"
      - "83:80"
    networks:
      chef:
        ipv4_address: 172.0.101.12
    container_name: node3
    domainname: codespaces.io
    hostname: node3
    restart: always

  node4:
    image: codespaces/chef-node-centos-6:v0.1.2
    ports:
      - "8084:8080"
      - "80:80"
    networks:
      chef:
        ipv4_address: 172.0.101.13
    container_name: node4
    domainname: codespaces.io
    hostname: node4
    restart: always
