# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.define "codespace" do |cs|
    cs.vm.hostname = "cs-ansible"
    cs.vm.network "private_network", ip: "192.168.56.101"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
    end  
    cs.vm.provision "shell", path: "scripts/docker.sh"
    cs.vm.provision "shell", path: "scripts/codespace.sh"
  end
 
end

